name: Trident
version: '1.0-SNAPSHOT'
main: org.minecraft.trident.Trident
api-version: '1.20'
load: STARTUP
authors: [ doxifieq ]
commands:
  fly:
    description: Toggles you or <player>'s flight mode.
    permission: trident.fly

  gamemode:
    description: Switches your game mode between creative and survival.
    permission: trident.gamemode
    aliases:
      - gm

  teleport:
    description: Teleport you to <player> or <player> to <player 2>
    permission: trident.teleport
    aliases:
      - tp

  tphere:
    description: Teleport <player> to you
    permission: trident.tphere
    aliases:
      - tph

  clearinventory:
    description: Clear the inventory of you or <player>
    permission: trident.clearinventory
    aliases:
      - clearinv
      - ci

  feed:
    description: Feeds you or <player>
    permission: trident.feed

  heal:
    description: Heals you or <player>
    permission: trident.heal

  give:
    description: Gives <player> <amount> of <item>
    permission: trident.give

  item:
    description: Gives you <amount> of <item>
    permission: trident.item
    aliases:
      - i

  day:
    description: Set time to 1000
    permission: trident.time

  night:
    description: Set time to 13000
    permission: trident.time

  tpa:
    description: Send a teleport request to <player>

  tpaccept:
    description: Accepts all pending teleport requests

  tpdeny:
    description: Denies all pending teleport requests